USE AFCON;

CREATE TABLE TEAMS(
CODE_COUNTRY CHAR(2) NOT NULL,
COUNTRY_NAME VARCHAR(30) NOT NULL,
CONTINENT CHAR(6) NOT NULL CHECK(CONTINENT= "AFRICA"),
CONSTRAINT PK_TEAMS PRIMARY KEY (CODE_COUNTRY)
); 
INSERT INTO TEAMS 
VALUES
('G1','GHANA','AFRICA'),
('N1','NIGERIA','AFRICA'),
('E2','EGYPT','AFRICA'),
('C9','CAMEROON','AFRICA'),
('K1','KENYA','AFRICA');



USE AFCON;
CREATE TABLE PLAYERS(
P_CODE CHAR (4) NOT NULL PRIMARY KEY,
P_NAME VARCHAR (30) NOT NULL,
PRO_CLUB VARCHAR(40) NOT NULL,
GOALS INT NULL,
COUNTRY_CODE CHAR (2),
CONSTRAINT FOREIGN KEY (COUNTRY_CODE)
      REFERENCES TEAMS (CODE_COUNTRY)
      ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PLAYERS
(P_CODE,P_NAME,PRO_CLUB,GOALS,COUNTRY_CODE)
VALUES
('G001','JUNIOR AGOGO','BIRMINGHAM','3','G1'),
("G002","Michael essien","Chelsea","4","G1"),
("n021","John obi michel","Chelsea","1","N1"),
("E039","mohammed zidane","Bayern Munich","2","E2"),
("C087","Samuel etoo","Barcelona","5","C9"),
("G004","Stephen Appiah","Ferneberche","2","G1"),
("N009","Hassan Osam","Al Alji","0","E2"),
("N032","Jj OKOCHA","chelsea NULL",NULL,"N1");

SELECT PLAYERS.P_NAME, TEAMS.COUNTRY_NAME,
        PLAYERS.PRO_CLUB
FROM PLAYERS,TEAMS;